### ISSUE TITLE
PointerContext updates are untraceable

### ISSUE THREAD

**Issue by Sylraka** [mcastiello/pixi-reactive#14]
**Action:**
Add the import of PointerContext and UseContext in different Components and initialize it with the following Code:
`
const { actualX, actualY, over, selected } = useContext(PointerContext);
`
The  PointerContext is not used yet.

**Expected behaviour:**
I'm not sure how it was originally intended to be used.
Should the PointerContext be initialized for the whole canvas and passed to the childrens on triggerEvents? This would be appropriate if the context can only be applied to the entire canvas. Like it is at the moment.

Or should it be initialized per child element in order to then update the global state at the appropriate events? That would be appropriate if the mouse tracking can be limited to the render area of the component.

Should it trigger the useEffect-lifecycle at every movement? I would prefer it if I could control it using self-defined events like onMouseEvents. This could also result in performance problems.

**Found behaviour:**
If I add this initialization in a primitive child-component like
```
const Test = () => {

    useEffect(() => {
        console.log('Test updated!');
    });

    const { actualX, actualY, over, selected } = useContext(PointerContext);

    return (
       <div></div> (/*or Pixi-elements, this makes no difference*/)
    );
}
```
And add this to some parent-component with a Pixi-Canvas, the useEffect-lifecycle triggers at every mouse-hover over the canvas, regardless to the render area of the child-element.

**Found behaviour:**
If I add this initialization (and a log for useEffect) to your PixiCanvasExample (https://mcastiello.github.io/pixi-reactive/#/index/components/pixicanvas/), the useEffect-lifecycle triggers at every ship-movement.

**Found behaviour:**
If I add this initialization to my parent-Component with the Pixi-Canvas-element, nothing happens. The chrome-debug-console shows that the PointerContext gets no data by hovering (see picture).
![Screenshot 2022-01-28 at 13 14 38](https://user-images.githubusercontent.com/27310921/151545416-a07dac47-4be7-4b6f-8e1d-2f8f987c8276.png)

I hope this informations are enough to find the bug. After one reload during the bug search, they were suddenly filled. And the parent component didn't trigger useEffect. However, I could not find any regularity for this behavior. I could not reproduce this functional state.

**Comment by Sylraka** [comment]
Your PixiCanvasExample, like my parent component, doesn't get any data for the PointerContext, useEffect is triggered from the reducer.
![Screenshot 2022-01-28 at 16 37 19](https://user-images.githubusercontent.com/27310921/151576053-c570c57f-c27e-40b9-8ff6-4968b5030568.png)


<br/>
<br/>

The hook is only triggered and the context is filled if the PointerContext is initialized in a ChildComponent of the PixiCanvas. But it triggers for the hole canvas.
![Screenshot 2022-01-28 at 16 51 45](https://user-images.githubusercontent.com/27310921/151578480-3565c119-5fe3-40ee-82af-d69f19def0bd.png)

**Comment by mcastiello** [comment]
yeah, only the child of the `PixiCanvas` will get the data from the context, and that is because it is the `PixiCanvas` that initialise it (well it initialise almost all of them), so you can't access the data from outside.
That is the intended behaviour, if you want to track the mouse movement form outside the canvas, I guess you can just add an `onMouseMove` (which is basically what the `PointerContext` does).

Let's put it this way, `PixiCanvas` must be the root component of every element/context/hook exported by this library. You can't use any of them outside. You can't use them even in the component that initialise the canvas, because that's how contexts work, they propagate from parent to child and `PixiCanvas` is the one element that initialise them all.

The idea behind this context is not to replace the various mouse event callbacks provided by each single element. It is literally to learn where and if the pointer is on the canvas. This can help you implementing gestures, or get the coordinates for new objects to create on click, or to simply design your own pointer that fits within your game design.

**Comment by Sylraka** [comment]
Hmm okey, I understand what you mean. But I don't try to track the mouse movement outside of the canvas. I'm trying to get the coordinates from the cursor (inside the canvas, inside the parent-child-hierarchy) to then link them to the mouse events.

Is there another way to get the current cursor-coordinates?

You say the PixiCanvas should initialise the PointerContext and propagate it to his children. The current behaviour looks different. Only a child of PixiCanvas can initialise the PointerContext. It propagate that to his parent, but not to the other childrens.
That means if I want to use the Context with every child of the canvas , I have to add one PointerContext for each child. Every context triggers his child-update by each mousemove inside the canvas. That's a big overhead...

**Comment by mcastiello** [comment]
I think you are confusing what initialising the context means with _using_ the context.

A context is initialised like this:
```jsx
<MyContext.Provider value={myContextData}>
  {children}
</MyContext.Provider>
```
while using the context is through the `useContext` hook.
```jsx
const myContextData = useContext(MyContext);
```
The only place you will see the `PointerContext` being initialised is within the `PixiCanvas` component.
What you get from the context are the X and Y coordinates of the pointer from the top/left corner of the canvas, and that context is not overridden by any of the child components, which means that each component will receive the exact same values.
The important is that the component using it, is a child of `PixiCanvas` (it doesn't have to be a first level child, it can be as nested as you like), there is no other way of using it.
```tsx
const PositionLogger: React.FC = () => {
  const { x, y } = useContext(PointerContext);
  useEffect(() => {
    console.log(`Position = X: ${x} = Y: ${y}`);
  }, [x, y]);
  return null;
};

const App: React.FC = () => {
  return <PixiCanvas>
    <PositionLogger />
  </PixiCanvas>;
};
```
and then just hover on the canvas.

**Comment by Sylraka** [comment]
You mean, the initialisation of `PointerContext` should be a child, in your example the PositionLogger? 
And how can I send the informations to the other childs? 

To send them with props like
```
<MyContext.Provider value={myContextData}>
  {children}
</MyContext.Provider>
```
is not possible if the value is in another component :(

**Comment by mcastiello** [comment]
I think you may be a bit confused on how React contexts work. Please refer to the documentation:
https://reactjs.org/docs/context.html
https://reactjs.org/docs/hooks-reference.html#usecontext

**Comment by Sylraka** [comment]
maybe you're right. 
Sometimes it is not easy to different between the own inability and bugs^^

But i still don't understand the pattern within your library. Isn't the "MyContext.Provider" and the "value={myContextData}" necessary here? Because the variable is declared in the child component I cannot use them. Did you have a static name for "MyContextData"?

The links you send tells only over the initialisation of Contexts inside the parent component. Or as a global variable.

Maybe you can add a second child in your example that wants to use the context through the useContext hook? I think that's the easiest way to describe the syntax.

**Comment by mcastiello** [comment]
The context provider is initialised by the `PixiCanvas` and it is available to all its children and any descendants. The syntax is always the same for each of the children.
```tsx
const { x, y } = useContext(PointerContext);
```
This syntax does NOT mean that you are initialising the context or adding some kind of listener in the canvas. It means that you are accessing data already elaborated and made available by the canvas to all its children.
It's not very different from accessing a Redux state. You are basically telling the `PixiCanvas` "hey, you have this data I'm really interested in, would you mind sharing it with me?"
There are other contexts provided by the `PixiCanvas` elements and they all work in the same way.
As described by the React documentation, contexts are a way to pass properties to elements that are not necessarily direct child of the context provider. If you ask me, it is also a good way of avoiding creating components with dozens of props that would otherwise be repeated across different component types.

In my example above, it doesn't matter where you put the `PositionLogger`, it will still work in the exact same way.

```tsx
const App: React.FC = () => {
  return <PixiCanvas>
    <PixiContainer>
      <PixiContainer>
        <PixiContainer>
          <PositionLogger />
        </PixiContainer>
      </PixiContainer>
    </PixiContainer>
  </PixiCanvas>;
};
```

**Comment by Sylraka** [comment]
Thats an interesting simplification you build with this context (and also with the others). How is it possible that React with your library only contains the data for PointerContext once? Because your Code in [this folder](https://github.com/mcastiello/pixi-reactive/blob/main/src/contexts/PointerContext.ts) creates the Context and I need to import the PointerContext variable for each child, I thought that he create a new PointerContext by each using.

Did you have some discord or slack channel? If you want to optimise your documentation maybe I can help you.

**Comment by mcastiello** [comment]
it's React magic  :D
you can use that data in every component you want, but it will only be created once and updated by the PixiCanvas. It works like an application state.
In fact, one of the easy way to avoid complex store libraries like Redux when you don't need all the extra bips and bops provided by that framework, is to use `useReducer` and store the state and the dispatch function in a React Context.
